// THIS FILE WAS AUTO-GENERATED BY https://github.com/kjk/w/cmd/gengo
package w

import (
	"golang.org/x/sys/windows"
	"syscall"
	"unsafe"
)

var (
	libshlwapi *windows.LazyDLL

	sHDeleteKeyW    *windows.LazyProc
	sHDeleteValueW  *windows.LazyProc
	sHGetValueW     *windows.LazyProc
	sHQueryInfoKeyW *windows.LazyProc
	sHQueryValueExW *windows.LazyProc
	sHSetValueW     *windows.LazyProc
)

func init() {
	libshlwapi = windows.NewLazySystemDLL("shlwapi.dll")
	sHDeleteKeyW = libshlwapi.NewProc("SHDeleteKeyW")
	sHDeleteValueW = libshlwapi.NewProc("SHDeleteValueW")
	sHGetValueW = libshlwapi.NewProc("SHGetValueW")
	sHQueryInfoKeyW = libshlwapi.NewProc("SHQueryInfoKeyW")
	sHQueryValueExW = libshlwapi.NewProc("SHQueryValueExW")
	sHSetValueW = libshlwapi.NewProc("SHSetValueW")
}

func SHDeleteKeyWSys(hkey HKEY, pszSubKey *uint16) uint32 {
	ret, _, _ := syscall.Syscall(sHDeleteKeyW.Addr(), 2,
		uintptr(hkey),
		uintptr(unsafe.Pointer(pszSubKey)),
		0,
	)
	return uint32(ret)
}

func SHDeleteValueWSys(hkey HKEY, pszSubKey *uint16, pszValue *uint16) uint32 {
	ret, _, _ := syscall.Syscall(sHDeleteValueW.Addr(), 3,
		uintptr(hkey),
		uintptr(unsafe.Pointer(pszSubKey)),
		uintptr(unsafe.Pointer(pszValue)),
	)
	return uint32(ret)
}

func SHGetValueWSys(hkey HKEY, pszSubKey *uint16, pszValue *uint16, pdwType *uint32, pvData unsafe.Pointer, pcbData *uint32) uint32 {
	ret, _, _ := syscall.Syscall6(sHGetValueW.Addr(), 6,
		uintptr(hkey),
		uintptr(unsafe.Pointer(pszSubKey)),
		uintptr(unsafe.Pointer(pszValue)),
		uintptr(unsafe.Pointer(pdwType)),
		uintptr(pvData),
		uintptr(unsafe.Pointer(pcbData)),
	)
	return uint32(ret)
}

func SHQueryInfoKeyWSys(hkey HKEY, pcSubKeys *uint32, pcchMaxSubKeyLen *uint32, pcValues *uint32, pcchMaxValueNameLen *uint32) uint32 {
	ret, _, _ := syscall.Syscall6(sHQueryInfoKeyW.Addr(), 5,
		uintptr(hkey),
		uintptr(unsafe.Pointer(pcSubKeys)),
		uintptr(unsafe.Pointer(pcchMaxSubKeyLen)),
		uintptr(unsafe.Pointer(pcValues)),
		uintptr(unsafe.Pointer(pcchMaxValueNameLen)),
		0,
	)
	return uint32(ret)
}

func SHQueryValueExWSys(hkey HKEY, pszValue *uint16, pdwReserved *uint32, pdwType *uint32, pvData unsafe.Pointer, pcbData *uint32) uint32 {
	ret, _, _ := syscall.Syscall6(sHQueryValueExW.Addr(), 6,
		uintptr(hkey),
		uintptr(unsafe.Pointer(pszValue)),
		uintptr(unsafe.Pointer(pdwReserved)),
		uintptr(unsafe.Pointer(pdwType)),
		uintptr(pvData),
		uintptr(unsafe.Pointer(pcbData)),
	)
	return uint32(ret)
}

func SHSetValueWSys(hkey HKEY, pszSubKey *uint16, pszValue *uint16, dwType uint32, pvData unsafe.Pointer, cbData uint32) uint32 {
	ret, _, _ := syscall.Syscall6(sHSetValueW.Addr(), 6,
		uintptr(hkey),
		uintptr(unsafe.Pointer(pszSubKey)),
		uintptr(unsafe.Pointer(pszValue)),
		uintptr(dwType),
		uintptr(pvData),
		uintptr(cbData),
	)
	return uint32(ret)
}
