// THIS FILE WAS AUTO-GENERATED BY https://github.com/kjk/winapigen
package w

import (
	"golang.org/x/sys/windows"
	"syscall"
	"unsafe"
)

var (
	libadvapi32 *windows.LazyDLL

	regOpenKeyExW   *windows.LazyProc
	regSetValueExW  *windows.LazyProc
	regCloseKey     *windows.LazyProc
	regDeleteKeyExW *windows.LazyProc
)

func init() {
	libadvapi32 = windows.NewLazySystemDLL("advapi32.dll")
	regOpenKeyExW = libadvapi32.NewProc("RegOpenKeyExW")
	regSetValueExW = libadvapi32.NewProc("RegSetValueExW")
	regCloseKey = libadvapi32.NewProc("RegCloseKey")
	regDeleteKeyExW = libadvapi32.NewProc("RegDeleteKeyExW")
}

func RegOpenKeyExWSys(hKey HKEY, lpSubKey *uint16, ulOptions uint32, samDesired uint32, phkResult *HKEY) uint32 {
	ret, _, _ := syscall.Syscall6(regOpenKeyExW.Addr(), 5,
		uintptr(hKey),
		uintptr(unsafe.Pointer(lpSubKey)),
		uintptr(ulOptions),
		uintptr(samDesired),
		uintptr(unsafe.Pointer(phkResult)),
		0,
	)
	return uint32(ret)
}

func RegSetValueExWSys(hKey HKEY, lpValueName *uint16, Reserved uint32, dwType uint32, lpData *uint8, cbData uint32) uint32 {
	ret, _, _ := syscall.Syscall6(regSetValueExW.Addr(), 6,
		uintptr(hKey),
		uintptr(unsafe.Pointer(lpValueName)),
		uintptr(Reserved),
		uintptr(dwType),
		uintptr(unsafe.Pointer(lpData)),
		uintptr(cbData),
	)
	return uint32(ret)
}

func RegCloseKeySys(hKey HKEY) uint32 {
	ret, _, _ := syscall.Syscall(regCloseKey.Addr(), 1,
		uintptr(hKey),
		0,
		0,
	)
	return uint32(ret)
}

func RegDeleteKeyExWSys(hKey HKEY, lpSubKey *uint16, samDesired uint32, Reserved uint32) uint32 {
	ret, _, _ := syscall.Syscall6(regDeleteKeyExW.Addr(), 4,
		uintptr(hKey),
		uintptr(unsafe.Pointer(lpSubKey)),
		uintptr(samDesired),
		uintptr(Reserved),
		0,
		0,
	)
	return uint32(ret)
}
