// THIS FILE WAS AUTO-GENERATED BY https://github.com/kjk/winapigen
package w

const (
	HKEY_CLASSES_ROOT                = 0x80000000
	HKEY_CURRENT_USER                = 0x80000001
	HKEY_LOCAL_MACHINE               = 0x80000002
	HKEY_USERS                       = 0x80000003
	HKEY_PERFORMANCE_DATA            = 0x80000004
	HKEY_PERFORMANCE_TEXT            = 0x80000050
	HKEY_PERFORMANCE_NLSTEXT         = 0x80000060
	HKEY_CURRENT_CONFIG              = 0x80000005
	HKEY_DYN_DATA                    = 0x80000006
	HKEY_CURRENT_USER_LOCAL_SETTINGS = 0x80000007
)

type HKEY HANDLE

const (
	DELETE                 = 0x00010000
	READ_CONTROL           = 0x00020000
	WRITE_DAC              = 0x00040000
	WRITE_OWNER            = 0x00080000
	ACCESS_SYSTEM_SECURITY = 0x01000000
	KEY_QUERY_VALUE        = 0x0001
	KEY_SET_VALUE          = 0x0002
	KEY_CREATE_SUB_KEY     = 0x0004
	KEY_ENUMERATE_SUB_KEYS = 0x0008
	KEY_NOTIFY             = 0x0010
	KEY_CREATE_LINK        = 0x0020
	KEY_WOW64_32KEY        = 0x0200
	KEY_WOW64_64KEY        = 0x0100
	KEY_WOW64_RES          = 0x0300
	KEY_READ               = 0x20019
	KEY_WRITE              = 0x20006
	KEY_ALL_ACCESS         = 0xF003F
	MAXIMUM_ALLOWED        = 0x02000000
)

const (
	REG_NONE                       = 0
	REG_SZ                         = 1
	REG_EXPAND_SZ                  = 2
	REG_BINARY                     = 3
	REG_DWORD                      = 4
	REG_DWORD_BIG_ENDIAN           = 5
	REG_LINK                       = 6
	REG_MULTI_SZ                   = 7
	REG_RESOURCE_LIST              = 8
	REG_FULL_RESOURCE_DESCRIPTOR   = 9
	REG_RESOURCE_REQUIREMENTS_LIST = 10
	REG_QWORD                      = 11
)
